### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by Iula79** [Iula79/Final-project#1]
@jasonseminara Please check out Readme and let me know about the proposal

**Comment by jasonseminara** [comment]
This is a great idea. I'd like to see the proposal more fleshed out to include user stories and list new features. This allows the client to compare proposed features of different contractors. 

I think the map isn't as important as the administrator's ability to 
1. manage bookings
2. automatically send out emails upon reservation add/change/delete. 

Please incorporate these two features into your project scope, move the maps feature into the backlog as a "nice-to-have".

Extra credit: A wireframe/mockup would also be nice.
